databases:
  - name: basketsekertest_DB
    databaseName: basketsekertest_db
    user: basketsekertest
    region: singapore

services:
  - type: web
    name: basketsekertest
    env: ruby
    region: singapore
    plan: free
    buildCommand: "bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;"
    startCommand: "bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: basketsekertest_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
