databases:
  - name: basketsekertest_DB
    databaseName: basketsekertest_db
    user: basketsekertest
    region: singapore

services:
  - type: web
    name: basketsekertest
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: basketsekertest_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
